# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.optimizers import Adam
from keras.utils import np_utils

# Loading dataset

In [2]:
(x_train, y_train),(x_test, y_test)=mnist.load_data()

In [3]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
y_train[56370]

5

# Reshaping Data

In [6]:
x_train=x_train.reshape(60000,28,28,1).astype('float32')
x_test=x_test.reshape(10000,28,28,1).astype('float32')

In [7]:
number_of_classes=10
y_train=np_utils.to_categorical(y_train,number_of_classes)
y_test=np_utils.to_categorical(y_test,number_of_classes)

In [9]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

# CNN Modelling

In [10]:
model = Sequential()
model.add(Conv2D(64,(3,3),input_shape=(28,28,1),activation='relu'))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(Flatten())
model.add(Dense(number_of_classes,activation='softmax'))

In [11]:
#Compiling the model
model.compile(loss='categorical_crossentropy', optimizer='Adam',metrics=['accuracy'])

In [12]:
#Training the model
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=5,batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 98s 52ms/step - loss: 0.1949 - accuracy: 0.9551 - val_loss: 0.0776 - val_accuracy: 0.9751
Epoch 2/5
1875/1875 [==============================] - 96s 51ms/step - loss: 0.0678 - accuracy: 0.9789 - val_loss: 0.0771 - val_accuracy: 0.9764
Epoch 3/5
1875/1875 [==============================] - 97s 52ms/step - loss: 0.0492 - accuracy: 0.9838 - val_loss: 0.0798 - val_accuracy: 0.9761
Epoch 4/5
1875/1875 [==============================] - 97s 52ms/step - loss: 0.0335 - accuracy: 0.9894 - val_loss: 0.0820 - val_accuracy: 0.9789
Epoch 5/5
1875/1875 [==============================] - 99s 53ms/step - loss: 0.0275 - accuracy: 0.9910 - val_loss: 0.1141 - val_accuracy: 0.9748


In [13]:
#Observing Metrics
metrics = model.evaluate(x_test,y_test,verbose=0)
print("Metrics (Test loss & Test Accuracy):")
print(metrics)

Metrics (Test loss & Test Accuracy):
[0.11410240828990936, 0.9747999906539917]


In [14]:
#Testing Model
prediction = model.predict(x_test[:4])
print(prediction)

[[2.1094198e-13 5.5422748e-24 2.1680712e-07 1.1617528e-07 5.0090340e-24
  6.8220881e-15 4.1911297e-25 9.9999964e-01 4.1039203e-12 2.6653020e-12]
 [2.7222304e-08 2.1875137e-06 9.9997175e-01 3.8455394e-09 4.7154843e-16
  5.1940645e-15 2.6131285e-05 3.6460269e-16 1.0082066e-08 3.1438327e-20]
 [1.9565664e-06 9.9744177e-01 1.3183362e-05 4.6555381e-11 1.5022462e-04
  4.2019337e-06 5.1117754e-10 6.2469270e-09 2.3886345e-03 7.2952494e-10]
 [1.0000000e+00 4.3669122e-15 1.7335777e-09 2.0180462e-14 1.2928257e-11
  6.8352368e-10 1.9345507e-09 3.0931957e-13 4.6068316e-11 7.9404598e-09]]


In [15]:
print(np.argmax(prediction,axis=1))
print(y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
#saving the model
model.save('models/mnistCNN.h5')